language: ruby
bundler_args: --without development
rvm:
  - ruby-head
  - 2.2
  - 2.1.1
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
env: TEST=true
before_install: git submodule update --init --recursive
script: bundle exec rake test
notifications:
  slack: middleman:JW9OvXmn1m3XrSERe8866nBR